version: 2

updates:
  - package-ecosystem: gradle
    directory: /Server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      spring:
        patterns:
          - org.springframework.boot*
          - org.springframework*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
